### PR TITLE
Fix issues for reivew.

### PR DESCRIPTION
**Pull request by junaruga**
Hi,
I could pass the review for the ticket https://bugzilla.redhat.com/show_bug.cgi?id=1326504#c35 .
This is the updated version. I wish you merge it.

By the way, I requested to create the htslib repository and branches.
https://bugzilla.redhat.com/show_bug.cgi?id=1326504#c35 .

But it was declined, because I am not the creator of the bugzilla ticket.
https://pagure.io/releng/fedora-scm-requests/issue/17763#comment-602780

So, I need to ask you to request the repository.
See https://bugzilla.redhat.com/show_bug.cgi?id=1326504#c35 review process document. This is what you need to do.

Thank you.

### CODE REVIEW

**Comment by SamStudio8** [comment]
Thanks Jun!

**Comment by junaruga** [comment]
Hi Sam, I am asking Fedora to get a "sponsor" role for my account to be a sponsor of you.
But I am not sure that I can get it.
https://pagure.io/packager-sponsors/issue/402

To create the repository on Fedora, I like you to get a sponsor from someone.

Here the documents.
* https://fedoraproject.org/wiki/Package_Review_Process
  > If you have not yet been sponsored, request sponsorship by raising an issue at https://pagure.io/packager-sponsors/
* https://fedoraproject.org/wiki/How_to_get_sponsored_into_the_packager_group

**Comment by SamStudio8** [comment]
Hi Jun!
Thanks for the help, if you are already a package author previously, I
don't mind if you would like to be the official maintainer as it means we
could bypass having to wait for sponsorship.

**Comment by junaruga** [comment]
Sure, okay. I will open own review request, closing current ticket like 

> https://bugzilla.redhat.com/show_bug.cgi?id=1326504#c37
> alternatively create your own review request and close this bug as duplicate and block this bug as FE-DEADREVIEW. If Sam request the package, he will be the maintainer and not you.

**Comment by SamStudio8** [comment]
Great. I think this makes the most sense. I am happy to help with future
maintenance but this means we won't have to go through the sponsor process.

**Pull request merged**
